package com.digithink.pos.erp.enumeration;

/**
 * Enumerates the supported ERP synchronization operations.
 */
public enum ErpSyncOperation {
	IMPORT_ITEM_FAMILIES, IMPORT_ITEM_SUBFAMILIES, IMPORT_ITEMS, IMPORT_ITEM_BARCODES, IMPORT_LOCATIONS,
	IMPORT_CUSTOMERS, EXPORT_CUSTOMER, EXPORT_TICKET, EXPORT_TICKET_LINE, UPDATE_TICKET, EXPORT_PAYMENT_HEADER,
	EXPORT_PAYMENT_LINE, EXPORT_RETURN, EXPORT_RETURN_LINE, EXPORT_SESSION
}
